name: for_statistics
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - scikit-learn
  - scikit-posthocs
